name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v2
        
    - name: Deploy to Firebase Hosting
      run: |
        echo 'Hello!!!'
        firebase deploy
