name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v2
    - name: Hello
      run: |
        echo 'Hello!!!'
    - name: Deploy to Firebase Hosting
      run: |
        firebase deploy --token=${{ secrets.FIREBASE_TOKEN }}
